// CLAUDE: This file defines the canonical API response shape. Every
// module MUST conform to it via the global ResponseInterceptor and
// AllExceptionsFilter. Adding a new error code is allowed; renaming
// or removing one is a breaking change for v1 consumers.

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
  SESSION_INVALID = 'SESSION_INVALID',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REPLAY = 'SESSION_REPLAY',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',
  OTP_TOO_MANY_ATTEMPTS = 'OTP_TOO_MANY_ATTEMPTS',
  OTP_NOT_FOUND = 'OTP_NOT_FOUND',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CANNOT_REMOVE_BOOTSTRAP_ADMIN = 'CANNOT_REMOVE_BOOTSTRAP_ADMIN',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  LISTING_NOT_FOUND = 'LISTING_NOT_FOUND',
  ADMIN_CONFIRM_REQUIRED = 'ADMIN_CONFIRM_REQUIRED',
  CANNOT_IMPERSONATE_SUPER_ADMIN = 'CANNOT_IMPERSONATE_SUPER_ADMIN',
  CANNOT_NEST_IMPERSONATION = 'CANNOT_NEST_IMPERSONATION',
  IMPERSONATION_ENDED = 'IMPERSONATION_ENDED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  MIME_NOT_ALLOWED = 'MIME_NOT_ALLOWED',
  MIME_MISMATCH = 'MIME_MISMATCH',
  SVG_UNSAFE_CONTENT = 'SVG_UNSAFE_CONTENT',
  GONE = 'GONE',
  EMAIL_PROVIDER_NOT_CONFIGURED = 'EMAIL_PROVIDER_NOT_CONFIGURED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  BALANCE_MISMATCH = 'BALANCE_MISMATCH',
  INVALID_IBAN = 'INVALID_IBAN',
  PAYOUT_NOT_PENDING = 'PAYOUT_NOT_PENDING',
  PAYOUT_NOT_APPROVED = 'PAYOUT_NOT_APPROVED',
  PAYMENT_INITIATION_FAILED = 'PAYMENT_INITIATION_FAILED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  REFUND_NOT_SUPPORTED_BY_PROVIDER = 'REFUND_NOT_SUPPORTED_BY_PROVIDER',
  INVALID_CALLBACK = 'INVALID_CALLBACK',
  REFUND_AMOUNT_EXCEEDS_AVAILABLE = 'REFUND_AMOUNT_EXCEEDS_AVAILABLE',
  CANNOT_REFUND_INSUFFICIENT_BALANCE = 'CANNOT_REFUND_INSUFFICIENT_BALANCE',
  REFUND_NOT_PENDING = 'REFUND_NOT_PENDING',
  PAYMENT_NOT_REFUNDABLE = 'PAYMENT_NOT_REFUNDABLE',
  MODULE_BOOT_FAILED = 'MODULE_BOOT_FAILED',
  CANNOT_BUY_OWN_LISTING = 'CANNOT_BUY_OWN_LISTING',
  ALREADY_OWNED = 'ALREADY_OWNED',
  LISTING_NOT_PURCHASABLE = 'LISTING_NOT_PURCHASABLE',
  INVALID_RUN_PACK = 'INVALID_RUN_PACK',
  EMPTY_CART = 'EMPTY_CART',
  CHECKOUT_VALIDATION_FAILED = 'CHECKOUT_VALIDATION_FAILED',
  ACCESS_DENIED_NOT_OWNER = 'ACCESS_DENIED_NOT_OWNER',
  BUNDLE_NOT_AVAILABLE = 'BUNDLE_NOT_AVAILABLE',
}

export interface ApiPagination {
  nextCursor?: string;
  limit: number;
}

export interface ApiMeta {
  pagination?: ApiPagination;
  // Modules may attach additional metadata under this index signature.
  [key: string]: unknown;
}

export interface ApiError {
  code: string;
  message: string;
  details?: unknown;
  // requestId is filled by the global filter once Phase 2D adds X-Request-Id.
  requestId?: string;
}

export interface ApiSuccess<T> {
  data: T;
  meta?: ApiMeta;
}

export interface ApiErrorResponse {
  error: ApiError;
}

export type ApiResponse<T = unknown> = ApiSuccess<T> | ApiErrorResponse;

// Type guard helpers for consumers
export function isApiSuccess<T>(r: ApiResponse<T>): r is ApiSuccess<T> {
  return 'data' in r;
}

export function isApiError<T>(r: ApiResponse<T>): r is ApiErrorResponse {
  return 'error' in r;
}
