// SECURITY: Action codes are part of the audit contract. Adding a new
// code is allowed; renaming or removing one breaks downstream queries and
// dashboards. Keep the catalog in sync with the dashboards in docs/.
export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  // AUTH_OTP_VERIFY is the declarative-decorator action for /auth/otp/verify;
  // the payload's `justCreated` discriminator distinguishes signup vs login
  // when readers prefer the one-row-per-attempt convention.
  AUTH_OTP_VERIFY: 'AUTH_OTP_VERIFY',
  SESSION_REFRESHED: 'SESSION_REFRESHED',
  LOGOUT: 'LOGOUT',
  PROFILE_COMPLETED: 'PROFILE_COMPLETED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_REPLAY_DETECTED: 'SESSION_REPLAY_DETECTED',
  ADMIN_USER_UPDATE: 'ADMIN_USER_UPDATE',
  ADMIN_USER_STATUS_CHANGED: 'ADMIN_USER_STATUS_CHANGED',
  ADMIN_ROLE_ASSIGNED: 'ADMIN_ROLE_ASSIGNED',
  ADMIN_ROLE_REMOVED: 'ADMIN_ROLE_REMOVED',
  IMPERSONATION_STARTED: 'IMPERSONATION_STARTED',
  IMPERSONATION_ENDED: 'IMPERSONATION_ENDED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',
  MAINTENANCE_TOGGLED: 'MAINTENANCE_TOGGLED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_METADATA_READ: 'FILE_METADATA_READ',
  FILE_DOWNLOADED: 'FILE_DOWNLOADED',
  NOTIFICATION_MARKED_READ: 'NOTIFICATION_MARKED_READ',
  PAYOUT_REQUESTED: 'PAYOUT_REQUESTED',
  PAYOUT_CANCELLED: 'PAYOUT_CANCELLED',
  PAYOUT_APPROVED: 'PAYOUT_APPROVED',
  PAYOUT_REJECTED: 'PAYOUT_REJECTED',
  PAYOUT_PAID: 'PAYOUT_PAID',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_CALLBACK_RECEIVED: 'PAYMENT_CALLBACK_RECEIVED',
  PAYMENT_REFUND_REQUESTED: 'PAYMENT_REFUND_REQUESTED',
  PAYMENT_REFUND_COMPLETED: 'PAYMENT_REFUND_COMPLETED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
